server: 
    port: 8092
eureka: 
   instance: 
       hostname: app2
   client:
       #registerWithEureka: false
       #fetchRegistry: false
       serviceUrl:  
          defaultZone: http://app1:8091/eureka/
     
     
   
        
            
    

       