server:
    port: 8091
eureka: 
   instance: 
       hostname: app1
   client: 
       registerWithEureka: false
       fetchRegistry: false
       serviceUrl:  
          defaultZone: http://app1:8091/eureka/
     
     
   
        
            
    

       